#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/ship?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1234
#
#  jpa:
#    database: mariadb
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#server:
#  port: 8980
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ship?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update